# Generated by Django 4.2.11 on 2024-05-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("core", "0020_modify_specs_materialized_views")]

    operations = [
        migrations.CreateModel(
            name="ValidatorSystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=255)),
                ("subtype", models.CharField(db_index=True, max_length=255)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("data", models.JSONField()),
                (
                    "validator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.validator"),
                ),
            ],
        ),
    ]
