# Generated by Django 4.2.11 on 2024-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_gpu_gpucount_hardwarestate_subnet_and_more"),
    ]

    operations = []
